# 1
01101000 01100101 01101010

# 2
15

# 3
2A

# 4 
1 = 1
10 = 2
100 = 4
1000 = 8
10000 = 16

# 5
A compiler takes the source code and turns it into machine code.

# 6
The program, typed by the user.

# 7
The machines native language, where numbers represents the commands
and data for the program.

# 8
First generation language is how the first computers worked by
switches, that were used to load ones or zeros into computer memory.
Each set of on/off switches represented a number, that would represent
data or an instruction for the computer to perform.

# 9
Secound generation language, is users enterring programs using
assembly language. Each command used a mnemonic, and a compiler would then change
the mnemonics into the numbers that represented the commands.

# 10
Third generation language uses a compiler. A compiler takes the
program typed in by the user (called source code) and turns it
into machine code. The programmer then runs the machine code.
If there are several pieces of source code in a program, they
can be linked together into one program with the use of a linker.
The linker is run on the machine code generated by the compiler
to generate a final program. This final program is what the
user runs, and the original source code is not needed.

# 11
Interpreters is programs that looks at the source code and
interpret it to machine language instructions on the fly.
It also allows the same programs to run on Windows, Mac,
and Unix computers, provided there is an interpreter available
for each platform.

# 12
# http://pypl.github.io/PYPL.html:
1 Java	
2 Python
3 PHP
4 C#
5 Javascript

# http://spectrum.ieee.org/computing/software/the-2016-top-programming-languages
1 C
2 Java
3 Python
4 C++
5 R

# http://www.inc.com/larry-kim/10-most-popular-programming-languages-today.html
1 Java
2 Python
3 C
4 Ruby
5 JavaScript

# 13
# Jobindex
C#
.NET
SQL
MSSQL
HTML5/JavaScript/AngularJS
C/C++

# thehub.dk
HTML, CSS & JavaScript
C#
Java
LESS
TypeScript
Clojure
ClojureScript
NoSQL

# 14
Syntax = The structure
Semantics = The meaning

# 15
My applewatch
Hardware = screen on a case with buttons on the side and wrist-strap.
Software = watchOS that allows the user to check messages, tracks activity
and so much more - on the wrist!!! 
